### ISSUE TITLE
Stats add up to 92%

### ISSUE THREAD

**Issue by tomconroy** [browserslist/browserslist-ga#18]
Hello, this tool is great! I'm looking for a way to generate a coverage number based on real usage. But when I import data from GA, the max coverage I can seem to get is around 92%

```sh
$ npx browserslist --coverage --stats="./browserslist-stats.json" "cover 100% in my stats"
These browsers account for 92.41% of all users in custom statistics
```

Which makes sense because the numbers in the stats file don't add up to 100:

```
> var stats = require('./browserslist-stats.json')
> Object.values(stats).reduce((acc, ss) => acc.concat(Object.values(ss)), []).reduce((acc, n) => acc + n, 0)
92.40687679083089
```

Is this expected? Where are the 8% are disappearing to?

**Comment by dmfrancisco** [comment]
Hi @tomconroy  👋 Sorry for taking so long to reply…

I think this is happening because those 8% are browsers that are not supported by Can I Use. If you go to [caniuse.com](https://caniuse.com) and click on "Settings" and "Import / From Google Analytics", do you get the same result? Those 8% will probably appear in the "Browsers not Included" column there too.
